### ISSUE TITLE
Not receiving  readytopaychangeCallBack event on Safari. I can see that working fine in chrome but not in Safari Version 15.4 (17613.1.17.1.13)

### ISSUE THREAD

**Issue by asha-tech** [google-pay/google-pay-button#132]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Component information:**

- Component
  - [ ] React component (`@google-pay/button-react`)
  - [ ] Custom element (`@google-pay/button-element`)
  - [x] Angular component (`@google-pay/button-angular`)
- Component version (e.g. 1.0.0):

**Environment:**

- Device (e.g. iPhone6):
- OS (e.g. iOS8.1):
- Browser (e.g. stock browser, safari)
- Country/region:

**Additional context** Add any other context about the problem here.

**Comment by asha-tech** [comment]
hi, anyone helping on this. we don't see this readytopaychangeCallBack/ readytopaychange event not receing in safari. We are blocked with the integration. please assist us.

**Comment by dmengelt** [comment]
Hello @asha-tech 
Are you able to share a link to a reproducer?

For me it works here: https://stackblitz.com/edit/google-pay-angular-dr6rne

<img width="2220" alt="Screen Shot 2022-12-08 at 10 42 39" src="https://user-images.githubusercontent.com/4389374/206413193-b5be4cb2-6cea-4e4c-9e71-a6aa54ddd250.png">

**Comment by dmengelt** [comment]
closing due to lack of feedback
