### ISSUE TITLE
Is there a way we can call isReadyToPay method using Angular Component? Need a way to find-out device capable of googlepay or not before my page starts display

### ISSUE THREAD

**Issue by asha-tech** [google-pay/google-pay-button#133]
This question is related to:

- [ ] React component (`@google-pay/button-react`)
- [ ] Custom element (`@google-pay/button-element`)
- [x] Angular component (`@google-pay/button-angular`)

**Comment by socsieng** [comment]
Depends on what you mean by _before my page starts to display_.

The `readyToPayChangeCallback` method or `readytopaychange` event can be used to handle the results of the component's internal `isReadyToPay` check.

**Comment by asha-tech** [comment]
yes. I tried these 2 methods. These are working fine in chrome and firefox but not in Safari. Don't see this event is being recieved in Safari? Please suggest how I need to solve this

**Comment by dmengelt** [comment]
Duplicate: See https://github.com/google-pay/google-pay-button/issues/132
