### ISSUE TITLE
The entrypoint for '@google-pay/button-angular' could not successfully be resolved

### ISSUE THREAD

**Issue by Zryru** [google-pay/google-pay-button#182]
**Describe the bug** 

Latest version v3.0.2 breaks in Angular with the following error

The entrypoint for '@google-pay/button-angular' could not successfully be resolved

**To Reproduce** Steps to reproduce the behavior:

1. Go to [StackBlitz](https://stackblitz.com/edit/google-pay-angular) obtained from  example page at https://github.com/google-pay/google-pay-button/tree/main/src/button-angular
2. Install the new version  
![image](https://user-images.githubusercontent.com/31626435/207316922-e962db4a-c74e-4354-9fe8-ff90a3ab4229.png)
3. See error

**Expected behavior** 

Described error should not happen

**Screenshots** If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/31626435/207317129-46d984cc-0b7e-4e96-8840-337e5508dc1e.png)

**Component information:**

- Component
  - [ ] React component (`@google-pay/button-react`)
  - [ ] Custom element (`@google-pay/button-element`)
  - [x] Angular component (`@google-pay/button-angular`)
- Component version (e.g. 1.0.0): 3.0.2

**Environment:**

- Browser (e.g. stock browser, safari)

**Comment by dmengelt** [comment]
@Zryru please switch to version 3.0.5 and try again.
