### ISSUE TITLE
Button color is always black

### ISSUE THREAD

**Issue by mjbour** [google-pay/google-pay-button#192]
Hi,

I've noticed today that the google pay button color is converted to black, although i'm setting the `buttonColor` property explicitly to be `white`, yet i'm getting the black version.

not sure what's wrong in this, i've tried also the stackBlitz example 
https://stackblitz.com/edit/google-pay-react?file=src%2FApp.js

it does show the same issue:

![image](https://user-images.githubusercontent.com/82119891/207841610-991a1b43-dd90-411f-9879-dae28522f171.png)

**Comment by dmengelt** [comment]
Hi @mjbour 
Thanks for reporting this. We just recently changed the Button to only be available in one color: https://developers.google.com/pay/api/web/guides/brand-guidelines#style

The grey border around the button will make sure that it works also on black backgrounds:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/4389374/208622422-606bab36-0002-4429-93e7-6bdc221018c4.png">

We will update the samples in the upcoming days!

**Comment by mjbour** [comment]
Thanks @dmengelt, that make sense.

**Comment by piotrponikowski** [comment]
Hi @dmengelt 
Is there changelog available? 

Is it possible to adjust border radius? I am interested in displaying google pay button as in previous version, to keep style matching my other UI elements.

**Comment by dmengelt** [comment]
Hi @piotrponikowski unfortunately there is no changelog available for this change. I'm sorry. It is currently not possible to adjust the border radius.

**Comment by dmengelt** [comment]
@piotrponikowski after feedback from partners we decided to revert this change. the white button variant is now available again.
