### ISSUE TITLE
Button with white background colour variant

### ISSUE THREAD

**Issue by lancedang64** [google-pay/google-pay-button#194]
Hi team, 

I see that the current API does not support a white background Google Pay Button. I came into this problem when integrating with our app which has a black background

It would be great if the Button component has an extra optional prop `theme` or `variant` to support the white background version

The alternative that I'm using in order to follow the brand guideline is to use the HTML-and-CSS-only version of the button which can be found here at https://developers.google.com/pay/india/api/otherapis/omnichannel/brand-guidelines

![image](https://user-images.githubusercontent.com/47963754/209902156-b6f587dd-24cd-4740-9d78-f655d8e8efd2.png)

**Comment by lancedang64** [comment]
I saw that the latest commit 65c98bad317423bd9d218f61e1f15f19a4f1497b removed the buttonColor prop because there is only 1 variant for the button now.

Also, I see that a similar issue was raised and addressed before at #192 

Hence closing this request

**Comment by dmengelt** [comment]
@lancedang64 after feedback from partners we decided to revert this change. the white button variant is now available again.
