### ISSUE TITLE
Different States for the Google Pay Button on React

### ISSUE THREAD

**Issue by damienteo** [google-pay/google-pay-button#218]
I am trying to show different states for the Google Pay Button for React (https://github.com/google-pay/google-pay-button/tree/main/src/button-react)

Is there a way to show that the button is disabled or loading?

I see the other issues and understand that this is possible on Angular, but there does not seem to be the option for customisation with the React version, based on the typescript setting.

**Comment by dmengelt** [comment]
@damienteo it would be great if you can help us with some more details and maybe link to to Angular functionality you are missing for the react version of the button.

**Comment by damienteo** [comment]
@dmengelt 

The issue where I saw the Angular functionality is: https://github.com/google-pay/google-pay-button/issues/107
It links to the following Stackoverflow question: https://stackoverflow.com/questions/70069077/google-pay-button-disable-on-condition/70070432#70070432

My bad, now that I read it further, I am not sure if it is a functionality offered directly by the package.

**Comment by dmengelt** [comment]
@damienteo Thank you very much for the clarifications. Yeah, at the moment this is not supported. Sorry for the circumstances.
