### ISSUE TITLE
Unhandled Exception Google is not Defined

### ISSUE THREAD

**Issue by jconleyCB** [google-pay/google-pay-button#219]
**Describe the bug** A clear and concise description of what the bug is.
The issue im seeing is when the google pay script doesnt load, an unhandled exception is thrown instead of passing the error to the `config.onError`.

**To Reproduce** Steps to reproduce the behavior:

1. Go to [this stackblitz](https://stackblitz.com/edit/google-pay-angular?file=package.json)
2. Click on update all dependencies to latest
3. inspect the page and block `https://pay.google.com/gp/p/`

**Expected behavior** A clear and concise description of what you expected to happen.
The `updateElement` function should have a check that google is defined before invoking `this.client = new google.payments.api.PaymentsClient(this.createClientOptions(this.config));`

**Screenshots** If applicable, add screenshots to help explain your problem.
<img width="435" alt="Screenshot 2023-04-19 at 10 05 35 AM" src="https://user-images.githubusercontent.com/104388326/233148687-60fd5982-e161-4520-a649-b1739dcde01a.png">

**Component information:**

- Component
  - [ ] React component (`@google-pay/button-react`)
  - [ ] Custom element (`@google-pay/button-element`)
  - [x] Angular component (`@google-pay/button-angular`)
- Component version (e.g. 1.0.0):

**Environment:**

- Device (e.g. iPhone6):
- OS (e.g. iOS8.1):
- Browser (e.g. stock browser, safari)
- Country/region:

**Additional context** Add any other context about the problem here.

**Comment by dmengelt** [comment]
@jconleyCB could you try with 3.0.6? We recently fixed a potentially related [issue](https://github.com/google-pay/google-pay-button/pull/127).

**Comment by jconleyCB** [comment]
Yep its still an issue in 3.0.6. My assumption is that even though the try-catch catches the error for loading the script it continues down to `this.updateElement()` and that tries to reference google without it being defined

**Comment by dmengelt** [comment]
@jconleyCB found the issue. will submit a fix.

**Comment by jconleyCB** [comment]
Thank you @dmengelt!

**Comment by dmengelt** [comment]
@jconleyCB please use version 3.0.8

**Comment by jconleyCB** [comment]
@dmengelt So after using version 3.0.8 for a few days I noticed some users still came across the `google` being undefined error. Im not sure if the script loading guarantees that `google` is available, should a check for `google` be added to the `updateElement()`, before it's [used](https://github.com/google-pay/google-pay-button/blob/0627cb9deb8c019aa5042b7198115fa560871812/src/lib/button-manager.ts#L232)?

**Comment by dmengelt** [comment]
Hi @jconleyCB very good point. Let me have a look at this.

**Comment by dmengelt** [comment]
@jconleyCB see #225
