### ISSUE TITLE
Type 'string' is not assignable to type 'PaymentMethodType'

### ISSUE THREAD

**Issue by speedDaemonAmber** [google-pay/google-pay-button#229]
I am trying to integrate this into my existing React app, which uses Typescript. I am getting  an incompatible types error: Type 'string' is not assignable to type 'PaymentMethodType'.

This is my payment request object where the payment method type is 'CARD', but it is not recognizing this as an acceptable value.

	const paymentRequest = {
		apiVersion: 2,
		apiVersionMinor: 0,
		allowedPaymentMethods: [
			{
				type: 'CARD',
				parameters: {
					allowedAuthMethods: ['PAN_ONLY', 'CRYPTOGRAM_3DS'],
					allowedCardNetworks: ['AMEX', 'DISCOVER', 'MASTERCARD', 'VISA']
				},
				tokenizationSpecification: {
					type: 'PAYMENT_GATEWAY',
					parameters: {
						gateway: 'cardconnect',
						gatewayMerchantId: gatewayMerchant,
					}
				}
			}
		],
		merchantInfo: {
			merchantId: '12345678901234567890',
			merchantName: 'Test Merchant',
		},
		transactionInfo: {
			totalPriceStatus: 'FINAL',
			totalPrice: paymentAmount.toString(),
			currencyCode: 'USD',
			countryCode: 'US'
		}
	};

Is there a way to get around this?

**Comment by dmengelt** [comment]
Hi @speedDaemonAmber Would it be possible to create a reproducer?

**Comment by speedDaemonAmber** [comment]
I created a repo [here](https://github.com/speedDaemonAmber/google-pay-test) that reproduces this issue.

**Comment by dmengelt** [comment]
@speedDaemonAmber could you try with:
```
const paymentRequest: google.payments.api.PaymentDataRequest = {
    apiVersion: 2,
    apiVersionMinor: 0,
    allowedPaymentMethods: [
      {
        type: 'CARD',
        parameters: {
          allowedAuthMethods: ['PAN_ONLY', 'CRYPTOGRAM_3DS'],
          allowedCardNetworks: ['MASTERCARD', 'VISA']
        },
        tokenizationSpecification: {
          type: 'PAYMENT_GATEWAY',
          parameters: {
            gateway: 'example',
            gatewayMerchantId: 'exampleGatewayMerchantID',
          }
        }
      }
    ],
    merchantInfo: {
      merchantId: '12345678901234567890',
      merchantName: 'Demo Merchant'
    },
    transactionInfo: {
      totalPriceStatus: 'FINAL',
      totalPriceLabel: 'Total',
      totalPrice: '100.00',
      currencyCode: 'USD',
      countryCode: 'US'
    }
  };
```

**Comment by speedDaemonAmber** [comment]
That worked. Thank you!
