### ISSUE TITLE
ReferenceError: Can't find variable: google (iOS)

### ISSUE THREAD

**Issue by johnratignier** [google-pay/google-pay-button#238]
**Describe the bug** Sometimes, sentry catches and raises a "ReferenceError: Can't find variable: google". Seems to happen only on iOS devices

**To Reproduce** Difficult to reproduce:

1. Load the GooglePay button (I suppose it happens during the mount)
2. Try to load multiple times...
3. ...Until the error occurs

**Expected behavior** No error

**Screenshots**
<img width="1446" alt="Capture d’écran 2023-07-13 à 10 47 52" src="https://github.com/google-pay/google-pay-button/assets/26454483/289f7bad-2df1-402c-b816-865348d4b725">

**Component information:**

- Component
  - [+] React component (`@google-pay/button-react`)
  - [ ] Custom element (`@google-pay/button-element`)
  - [ ] Angular component (`@google-pay/button-angular`)
- Component version (e.g. 1.0.0):

**Environment:**

- Device: All iPhones
- OS: All iOS version
- Browser: Safari / Mozilla iOS / Chrome iOS
- Country/region: Europe

**Additional context** Add any other context about the problem here.

**Comment by dmengelt** [comment]
@johnratignier you are using the latest version of the react component. Right?

**Comment by johnratignier** [comment]
Arf no, we are using 3.0.6. I just see that has been handlef in 3.0.9. Big sorry for that
