### ISSUE TITLE
Documentation for preFetch paymentData

### ISSUE THREAD

**Issue by sverraest** [google-pay/google-pay-button#24]
**Is your feature request related to a problem? Please describe.** 
Lacking documentation for https://developers.google.com/pay/api/web/reference/client#prefetchPaymentData

**Describe the solution you'd like** A clear and concise description of what you want to happen.
Add use cases or code examples for https://developers.google.com/pay/api/web/reference/client#prefetchPaymentData

**Comment by socsieng** [comment]
Thanks, I'll pass on the feedback.

WRT `prefetchPaymentData` in this library, this is automatically enabled for you. Not that from https://developers.google.com/pay/api/web/reference/client#prefetchPaymentData:

> Prefetch optimizations are currently available on Chrome for Android. Other browsers and platforms to follow.
