### ISSUE TITLE
issue when set locale in Arabic

### ISSUE THREAD

**Issue by sajasbana** [google-pay/google-pay-button#251]
Dears,
there is issue when gpay button we set locale in Arabic
reference link:
https://developers.google.com/pay/api/web/guides/resources/customize

it should be like below imaeg
![image](https://github.com/google-pay/google-pay-button/assets/34976854/a9b5289f-27df-4eaa-be47-daae73c6aa1b)

**Comment by dmengelt** [comment]
@sajasbana thank you very much for reporting this. we are aware and are looking into it.

**Comment by ibrahimchiha** [comment]
@dmengelt has this been resolved? Currently facing the same issue

**Comment by dmengelt** [comment]
@ibrahimchiha unfortunately not yet 😢 will keep you posted...

**Comment by dmengelt** [comment]
@sajasbana / @ibrahimchiha is the translation only wrong for button type `pay` or others as well?

**Comment by sajasbana** [comment]
@dmengelt 
translation is right but letters are reversed

**Comment by dmengelt** [comment]
@sajasbana could you check again and let me know if the translations look good to you now?

**Comment by sajasbana** [comment]
@dmengelt 
Thanks for your effort it is almost done, but still some buttons have the same issue (pay and subscribe) buttons
![image](https://github.com/google-pay/google-pay-button/assets/34976854/ec003afb-0c54-4374-8835-24a88436f70f)

**Comment by dmengelt** [comment]
@sajasbana can you try to clear your cache and try again. For me it looks different for `pay` and `subscribe`:
<img width="686" alt="Google Pay button with button type pay" src="https://github.com/google-pay/google-pay-button/assets/4389374/7cfaca80-f4e1-4712-b038-dabe8550ef83">

<img width="664" alt="Google Pay button with button type subscribe" src="https://github.com/google-pay/google-pay-button/assets/4389374/8cf373cb-25f2-497f-a4a0-5d657d1f925d">

**Comment by sajasbana** [comment]
@dmengelt 
Thanks it is working
we can close this issue

**Comment by dmengelt** [comment]
Great. Thanks for your help @sajasbana
