### ISSUE TITLE
How can i remove min-width from google-pay-button on CSS or how can i customize style?

### ISSUE THREAD

**Issue by jalalbmnf** [google-pay/google-pay-button#252]
<img width="1373" alt="Screenshot 2023-10-18 at 18 45 45" src="https://github.com/google-pay/google-pay-button/assets/53921355/3d96330f-3dd7-494b-8eb2-c89db45d1ec5">

**Comment by jalalbmnf** [comment]
I am trying to change the value of the min-width property but it is not possible, also I checked Google Pay doc. for customize Google Pay button and I wrote with documentation but it is not working properly

**Comment by dmengelt** [comment]
Correct we are currently not supporting this.

**Comment by jalalbmnf** [comment]
Then how can I solve this problem? Or is there any task for the future?

**Comment by dmengelt** [comment]
What kind of problem? Could you share a screenshot of your UI where you try to show a Google Pay button?

**Comment by jalalbmnf** [comment]
> What kind of problem? Could you share a screenshot of your UI where you try to show a Google Pay button?

When I added buttonType attribute to Google-pay-button there was no way to decrease min-width

**Comment by dmengelt** [comment]
@jalalbmnf I do understand this. However, what is the reason you are trying to decrease min-width? Could you maybe share a screenshot of your UI?

**Comment by jalalbmnf** [comment]
<img width="525" alt="Screenshot 2023-10-24 at 13 44 13" src="https://github.com/google-pay/google-pay-button/assets/53921355/f666732f-6c69-4e29-9250-cb4707c4210a">

I want to create this for small screens, and they should be small to stand side by side

**Comment by dmengelt** [comment]
thanks @jalalbmnf - unfortunately this is currently not possible for the dynamic button (showing the card network icon and last 4 digits of the users card). 

You can switch to `buttonType=pay`. There you have a bit more flexibility if it comes to the `width` of the button.

**Comment by jalalbmnf** [comment]
It is not possible with `buttonType=pay` to decrease max-width.
