### ISSUE TITLE
Get token empty in tokenizationData data from onLoadPaymentData method

### ISSUE THREAD

**Issue by kukadiyaAni** [google-pay/google-pay-button#257]
I set the Google Pay button with Braintree but I'm getting a token that is empty in onLoadPaymentData method  

This question is related to:

- [x] React component (`@google-pay/button-react`)
- [ ] Custom element (`@google-pay/button-element`)
- [ ] Angular component (`@google-pay/button-angular`)

```<GooglePayButton
        environment="TEST"
        buttonType="buy"
        paymentRequest={{
          apiVersion: 2,
          apiVersionMinor: 0,
          merchantInfo: {
            merchantId: "google merchant id",
            merchantName: "Prank Caller",
          },
          allowedPaymentMethods: [
            {
              type: "CARD",
              parameters: {
                allowedAuthMethods: ["PAN_ONLY", "CRYPTOGRAM_3DS"],
                allowedCardNetworks: ["MASTERCARD", "VISA"],
              },
              tokenizationSpecification: {
                type: "PAYMENT_GATEWAY",
                parameters: {
                  gateway: "braintree",
                  "braintree:clientKey": "clien token",
                  "braintree:apiVersion": "3",
                  "braintree:sdkVersion": "3.97.2",
                  "braintree:merchantId": "test id", // test
                },
              },
            },
          ],
          transactionInfo: {
            totalPriceStatus: "FINAL",
            totalPriceLabel: "Total",
            totalPrice: "1.00",
            currencyCode: "USD",
            countryCode: "US",
          },
        }}
        onLoadPaymentData={(paymentRequest) => {
          console.log("load payment data", paymentRequest);
        }}
      />

```
Thanks in advance any can help me on this

**Comment by dmengelt** [comment]
@kukadiyaAni make sure to use the correct braintree parameters. As an example, did you use the correct `braintree:merchantId`?

Also, if you could create a re-producer for me that would help a lot.

**Comment by kukadiyaAni** [comment]
@dmengelt Thanks for reply, braintree:merchantId is correct and verified if directly did using Braintree method it's worked

**Comment by dmengelt** [comment]
thanks @kukadiyaAni 

Could you try with the following braintree parameters:

```
'braintree:apiVersion': 'v1',
'braintree:sdkVersion': 'braintree.client.3.40.0',
'braintree:merchantId': 'your-merchant-id',
'braintree:clientKey': 'sandbox_1234'
```

For the `braintree:clientKey` try to use a [tokenization key](https://developer.paypal.com/braintree/docs/guides/authorization/tokenization-key/javascript/v3/#obtaining-a-tokenization-key) generated in [Braintree's portal](https://sandbox.braintreegateway.com/login) 

<img width="1541" alt="Screenshot 2023-10-19 at 16 37 47" src="https://github.com/google-pay/google-pay-button/assets/4389374/17f9e4a7-ee1b-4eab-8c08-82b685f5fc7b">

**Comment by kukadiyaAni** [comment]
@dmengelt I still get the same issue token is empty but I fixed by preventing native click of the button and using Braintree code to generate process payment

**Comment by dmengelt** [comment]
@kukadiyaAni what do you mean with "preventing native click"? Could you share a code example?
