### ISSUE TITLE
Missing Border

### ISSUE THREAD

**Issue by PrinzJuliano** [google-pay/google-pay-button#262]
**Describe the bug** A clear and concise description of what the bug is.

Currently, there is a major discrepancy between the Brand Guidelines for Web and Android, the official Demo Page, and this library. 
The Brand Guidelines for Web do feature buttons without a border.
The Brand Guidelines for Android (while not mentioning it) clearly show in some of the dark buttons a rgb(117, 117, 117) #757575 border.
This library does not currently add this border.

Thus, following the Integration Checklist closely will yield a rejection from the Google Pay submission when using a Web to Native Framework like Ionic.

**To Reproduce** Steps to reproduce the behavior:

1. Go on https://developers.google.com/pay/api/web/guides/brand-guidelines#style
2. Select Color black, type pay
3. See that the button does not have a border 
4. Go to https://developers.google.com/pay/api/android/guides/brand-guidelines#assets
5. The Buttons have a border around them
6. Go to the https://developers.google.com/pay/api/android/guides/resources/payment-button-static-assets page
  1. These are the official Android Assets when you can't use the API. They do not feature a border!

**Expected behavior** A clear and concise description of what you expected to happen.
I expect both Guidelines to be the same, or at least give me options to enable the border when detecting android.

**Screenshots** If applicable, add screenshots to help explain your problem.
Android Button:
<img width="627" alt="image" src="https://github.com/google-pay/google-pay-button/assets/1338788/9af21d1c-0005-4a6a-9c7a-16fef0613df7">

Web Button:
<img width="274" alt="image" src="https://github.com/google-pay/google-pay-button/assets/1338788/f1e2c088-1934-4dc7-924d-9c1dbbef5486">

Web Button on Android:
<img width="368" alt="Bildschirmfoto 2023-12-12 um 10 56 20" src="https://github.com/google-pay/google-pay-button/assets/1338788/404b116b-206b-4ecf-996d-99f754c3d501">

**Component information:**

- Component
  - [X] React component (`@google-pay/button-react`)
  - [X] Custom element (`@google-pay/button-element`)
  - [X] Angular component (`@google-pay/button-angular`)
- Component version (e.g. 1.0.0): 3.0.10

**Environment:**

- Device: Google Pixel 7
- OS:  Android 14 SDK 34
- Browser: Chrome as Capacitor App
- Country/region: Germany

**Additional context** Add any other context about the problem here.
This is not a bug. Just different standards for Guidelines concerning the same UI Element.

**Comment by dmengelt** [comment]
@PrinzJuliano thank you for reporting this:

1. we are aware of this and will release a version of the web button with a border soon.
2. The static assets for android page has a warning at the top. however, you should not get a rejection because of this.

could you give me some more context regarding the rejection?

**Comment by PrinzJuliano** [comment]
Right now, we are using IonicFramework and Integrate the Google Pay buyflow using Stripe as a Gateway.
The screenshot of the App (labeled Web Button on Android) got flagged as non compliant.

The original response we got was:
> Hi amicaldo GmbH,
>
> We have an update on your recent Google Pay API integration submission.
>
> Please revisit your integration and ensure that you are using our approved Google Pay Button.
> Web: https://developers.google.com/pay/api/web/guides/brand-guidelines#payment-buttons
> Android: https://developers.google.com/pay/api/android/guides/brand-guidelines#payment-buttons
> 
> All Google Pay payment buttons on your site must adhere to our brand guidelines, which include, but aren't limited to, the > following requirements:
> 
> - The size must be relative to other similar buttons or elements of the page. You can adjust the button size with the buttonSizeMode option of the createButton API.
> - The button color must contrast with the background color of the area that surrounds it.
> - The button must maintain the minimum amount of clear space on all sides of it.
> 
> We provide the CreateButton API that will automatically ensure that your Google Pay button adheres to our brand guidelines.
> Web:[ https://developers.google.com/pay/api/web/guides/resources/customize](https://developers.google.com/pay/api/web/guides/brand-guidelines#payment-buttons)
> Android:[ https://developers.google.com/pay/api/android/guides/resources/update-to-new-payment-button](https://developers.google.com/pay/api/android/guides/brand-guidelines#payment-buttons)
> 
> Please make or provide the appropriate updates, and re-submit your integration again through the [Google Pay & Wallet Console](https://pay.google.com/business/console). If the above marketing review feedback cannot be implemented because you are using a dedicated Plugin or provided hosted checkout solution from your Payment Service Provider, please reach out to us by responding to this email.
> 
> Thank you for submitting your integration through the Google Pay & Wallet Console. It’s been a pleasure working with you.
> 

This highly confused us.

We wrote to the support with the reply:

> Thanks for your update,
> 
> I am not sure how to proceed.
> 
> The brand guidelines clearly show border around the buttons, but none of the written guidelines mention borders, only clear space around the button (which we satisfy).
> 
> Additionally, all material provided on the usage of the Google Pay button API does not include any border as well. (The Button appears to be plain black and inspecting the HTML, the Button has a 0px width black border, as does our integration)
> 
> For example: https://developers.google.com/pay/api/web/guides/resources/demos
> 
> I have used the Google Pay Button API to ensure the integration complies with all brand guidelines. I do not modify any of the styles beyond the settings provided by the API.
> 
> Could you provide the links to the documentation on the Google Pay Button API where I can set borders?
> 
> Or am I completely mistaken by your suggestion and I should change something else?
> 
> 
> I am looking forward to your reply.

Which we got the reply:
> Hi,
> 
> Thanks for update.
> 
> Please refer to the attached screenshot and update the Google Pay button as per our brand guidelines boarder should be present around the button.
> 
> Best,
> Dharani
> 
> The Google Pay API Support Team

![4g44WJvrzGE82vw](https://github.com/google-pay/google-pay-button/assets/1338788/a5248342-ae22-44ca-88fc-2f54047a61b5)

This confused us even more, as we were using the createButton api

But further communication only hinged on the border missing.

**Comment by dmengelt** [comment]
thanks @PrinzJuliano for sharing the details.

your integration is now approved.

**Comment by PrinzJuliano** [comment]
Thanks for your help.
