### ISSUE TITLE
Open Google Pay App for Payment

### ISSUE THREAD

**Issue by NayakPenguin** [google-pay/google-pay-button#263]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem
is. 
I am developing a QR payment system for a restaurant, aiming to facilitate payment processing for users upon completing their orders. I intend for users to be seamlessly directed to the Google Pay app, where they can view and complete the required payment. And hence don't have to give their card details. 

**Describe the solution you'd like** A clear and concise description of what you want to happen.
1. The user is directed to the Google Pay app where they will get the payment request. 
2. The website should be able to know if the payment is completed.

**Comment by dmengelt** [comment]
Not an issue for the Google Pay button
