### ISSUE TITLE
Disable ugly ad `Get google pay emails with exclusive offers, tips and invitations to give feedback` in Google Pay Sheet

### ISSUE THREAD

**Issue by nolimitdev** [google-pay/google-pay-button#269]
Add a feature to the API where developers can disable unsightly ad `Get google pay emails with exclusive offers, tips and invitations to give feedback`. Avoid including advertisements such as competitive payment services, as they clutter the payment interface, which should remain clean and minimalist.

**Comment by dmengelt** [comment]
@nolimitdev we do understand your concerns. I will bring this up with the team.
