### ISSUE TITLE
Google Pay button unresponsive to click event

### ISSUE THREAD

**Issue by paymentplugins** [google-pay/google-pay-button#270]
**Describe the bug**
In the last 48 hrs our so, the web version of the Google Pay button has become unresponsive to click events. You can observe this issue on Google's GPay demo page. [Google Pay Demo](https://developers.google.com/pay/api/web/guides/resources/demos).

If you wait about 3 seconds until the button fully loads and then attempt to click the button, the wallet does not open. This issue appears to be affecting every integration that uses the `https://pay.google.com/gp/p/js/pay.js` script.

The button is clickable when the page first loads, but after a few seconds, that is when it becomes unresponsive. If you carefully hover the cursor over the border of the GPay button until the pointer appears, you can click and open the wallet. So only the border is responsive to the click event, when the entire button should respond.

Payment Plugins is creating the report here because Google's API team doesn't appear to provide an easy way to notify them of bugs or escalate technical issues.

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://pay.google.com/gp/p/js/pay.js
2. Click on any one of the GPay demo buttons after it has fully loaded.
3. Note that the click event does not result in the GPay wallet opening.

**Expected behavior** 
The GPay wallet should open when the button is clicked.

**Component information:**

- Component
https://pay.google.com/gp/p/js/pay.js - which all of your elements are likely backed by.

**Environment:**
Issue is present on all devices and browsers.

**Comment by dmengelt** [comment]
this was a bug on our side and is now resolved. sorry for the troubles.

**Comment by paymentplugins** [comment]
@dmengelt Thank you for the update. We will let all of the merchants using our platform know the issue has been resolved.
