### ISSUE TITLE
googlepay button shows different behavior 

### ISSUE THREAD

**Issue by sajasbana** [google-pay/google-pay-button#271]
Hi dears,

we notice that something changed in google pay, i have strange issue and don't know why this happen, it was working and we did not change thing.

1- it our demo, google show my live card last 4 digit, but when click it only shows test cards
![image](https://github.com/google-pay/google-pay-button/assets/34976854/532db012-7370-451b-a50d-e9f3a20e4310)

2- how can i have last 4 digit and show only pay with google like old button?

3- when i open the link in incognito mode, it shows buy button, i only use pay!!
![image](https://github.com/google-pay/google-pay-button/assets/34976854/3d8d6d59-d49b-486a-b6c9-d43540908033)

but in your demo website: https://developers.google.com/pay/api/web/guides/resources/customize
this should be the behaviur
![image](https://github.com/google-pay/google-pay-button/assets/34976854/3e374cbd-4ccf-4d2d-af48-7bf9a95df68b)

**Comment by dmengelt** [comment]
@sajasbana thanks for reporting this. we rolled back a change and you should be able to see the "Pay with GPay" button again in case the dynamic data (card network icon + last 4 digits) are not available.

**Comment by sajasbana** [comment]
@dmengelt 
now working Thanks
