### ISSUE TITLE
allowedCardNetworks doesn't work

### ISSUE THREAD

**Issue by Leobitscube** [google-pay/google-pay-button#274]
When using version of 3.0.10, I'm trying to set allowedCardNetworks as ['VISA', 'MASTERCARD', 'AMEX'], other types of bank card are display also. I tried to copy   [examples](https://github.com/google-pay/google-pay-button/blob/main/examples/vue/src/components/StaticExample.vue) and doesn't work either. I'm in TEST env though.

**Comment by dmengelt** [comment]
@Leobitscube please provide a full example and also a screenshot on what the Google Pay sheet looks like.

**Comment by Leobitscube** [comment]
> @Leobitscube please provide a full example and also a screenshot on what the Google Pay sheet looks like.

The examples that you provided doesn't work either

**Comment by dmengelt** [comment]
Alright. Thanks. I will look into it.

**Comment by dmengelt** [comment]
@Leobitscube are you currently part of the following group? https://groups.google.com/g/googlepay-test-mode-stub-data

If yes, if you leave the group and try again. Does `allowedCardNetworks` work again?

**Comment by dmengelt** [comment]
@Leobitscube it is a bug on our side if the user is part of the ["test card suite"](https://groups.google.com/g/googlepay-test-mode-stub-data) group. We have a fix ready and we should be able to deploy soon. I will keep you posted. Sorry for the circumstances.

**Comment by dmengelt** [comment]
@Leobitscube this issue is now fixed
