### ISSUE TITLE
Gpay button text

### ISSUE THREAD

**Issue by sajasbana** [google-pay/google-pay-button#288]
Dears
Is possible to make Google pay text as string not image?

This gives ability to more control on the button

**Comment by dmengelt** [comment]
@sajasbana could you help me to understand what exactly you are trying to achieve?

**Comment by sajasbana** [comment]
hi @dmengelt 
in the below screenshot, I have 3 buttons all the same height, but in Google pay, the font size is large because it is an image, what if I want to decrease font size to be similar or closer to other buttons:

![image](https://github.com/google-pay/google-pay-button/assets/34976854/d351bb60-0ce7-42ca-835b-97ce1f1edd3b)

for now I decreased all button height, but if there an option to control font size will be good feature.

**Comment by dmengelt** [comment]
@sajasbana unfortunately this is not possible - so sorry for the circumstances.
