### ISSUE TITLE
Always throwing postMessage error

### ISSUE THREAD

**Issue by jimmleon** [google-pay/google-pay-button#299]
I am using the Google Pay web component, in a Vue implementation.
Each time the component renders, the onError callback is triggered with the following ErrorEvent:

```
message: "Failed to execute 'postMessage' on 'Window': [object Array] could not be cloned"
name: "DataCloneError"
```
This also happens to the [stackblitz example](https://stackblitz.com/edit/google-pay-vue?file=src%2FApp.vue)

Any ideas why this is happening and how to fix?

**Comment by dmengelt** [comment]
@jimmleon I can't reproduce this on my side. What browser are you using?

**Comment by jimmleon** [comment]
Google Chrome 127.0.6533.73
Also happens in Firefox.

Doesn't this error appear to you in the documentation's [Stackblitz example](https://stackblitz.com/edit/google-pay-vue?file=src%2FApp.vue)?

Check screenshot:
![image](https://github.com/user-attachments/assets/4fb08087-715c-4452-a638-a5b7b04eed66)

**Comment by dmengelt** [comment]
@jimmleon No this error doesn't appear for me with the Stackblitz example on Chrome

**Comment by jimmleon** [comment]
For anyone else who may be facing this, 
it seems that the error will occur if the `paymentRequest` does not contain raw data, but proxy objects instead (reactive, computed etc).
In my implementation (Vue 3), some data (like the `allowedAuthMethods` and `allowedCardNetworks`) were computed properties, and this resulted to the `postMessage` not being able to properly handle the proxy object.

So I needed to use the [toRaw()](https://vuejs.org/api/reactivity-advanced.html#toraw)
