### ISSUE TITLE
Third-party cookie warning

### ISSUE THREAD

**Issue by oleksandrZhe** [google-pay/google-pay-button#313]
Currently, the Chrome browser (Version 129.0.6668.101) displays a warning about third-party cookies:
```
Third-party cookie will be blocked in future Chrome versions as part of Privacy Sandbox.
```
It's unclear whether the Google Pay button will stop working once Chrome starts blocking third-party cookies. In any case, it seems advisable to take action, either to prevent future issues or to change the current behavior so that this warning disappears.

This question is related to:

- [x] React component (`@google-pay/button-react`)
- [ ] Custom element (`@google-pay/button-element`)
- [ ] Angular component (`@google-pay/button-angular`)

**Comment by dmengelt** [comment]
Hi. The Google Pay button will continue to work even once Chrome starts to fully block 3rd party cookies.

**Comment by oleksandrZhe** [comment]
Good to know. But it would be great to get rid of warnings, as they spaming to often.
