### ISSUE TITLE
Error OR_BIBED_06 / worldlinesaferpay gateway

### ISSUE THREAD

**Issue by 2one2** [google-pay/google-pay-button#323]
I'm setting up Google Pay for Worldlinesaferpay gateway, and I get this error in production mode. 

"Something went wrong This merchant is having trouble accepting your payment right now. Try using a different payment method. [OR_BIBED_06] OR_BIBED_06"

On test environment I can complete the payment without issues.
Worldlinesaferpay support confirmed that tokenizationSpecification params are correct.

paymentRequest props:
```
{
    "apiVersion": 2,
    "apiVersionMinor": 0,
    "allowedPaymentMethods": [
        {
            "type": "CARD",
            "parameters": {
                "allowedAuthMethods": [
                    "PAN_ONLY",
                    "CRYPTOGRAM_3DS"
                ],
                "allowedCardNetworks": [
                    "MAESTRO",
                    "MASTERCARD",
                    "VISA"
                ]
            },
            "tokenizationSpecification": {
                "type": "PAYMENT_GATEWAY",
                "parameters": {
                    "gateway": "worldlinesaferpay",
                    "gatewayMerchantId": "GATEWAY_MERCHANT_ID"
                }
            }
        }
    ],
    "merchantInfo": {
        "merchantId": "GOOGLE_PAY_MERCHANT_ID"
    },
    "transactionInfo": {
        "totalPriceStatus": "FINAL",
        "totalPriceLabel": "Total",
        "totalPrice": "1.00",
        "currencyCode": "EUR"
    }
}
```

This question is related to:

- [ ] React component (`@google-pay/button-react`)
- [x] Custom element (`@google-pay/button-element`)
- [ ] Angular component (`@google-pay/button-angular`)

**Comment by dmengelt** [comment]
Any chance you can share the `GOOGLE_PAY_MERCHANT_ID` and the Google account (email) you used for the transaction?

You can [follow me on X](https://x.com/dmengelt) and drop me a private message if this is better for you.
