### ISSUE TITLE
Add ability to know if the browser is supported

### ISSUE THREAD

**Issue by fmendoza** [google-pay/google-pay-button#58]
How can we know in advance if the browser supports gpay?

I looked into the official documentation and it seems the correct way is to create an instance of the `PaymentsClient`, call the `isReadyToPay` method, and wait for the async result.

```js
const paymentsClient = new google.payments.api.PaymentsClient({environment: 'TEST'});
paymentsClient.isReadyToPay(isReadyToPayRequest)
.then(function(response) {
      if (response.result) {
        // add a Google Pay payment button
      }
    })
    .catch(function(err) {
      // show error in developer console for debugging
      console.error(err);
    });
```

This question is related to:

- [x] Angular component (`@google-pay/button-angular`)
- [ ] React component (`@google-pay/button-react`)
- [ ] Custom element (`@google-pay/button-element`)

**Comment by socsieng** [comment]
You can either add a handler to `readyToPayChangeCallback` listen to the `readytopaychange` event.

The button's behavior is to not be displayed if the browser doesn't support Google Pay, but you can use either method described above to apply additional logic.

Please let me know if this meets your requirement.

**Comment by socsieng** [comment]
Please feel free to reopen if this doesn't answer your question.
