### ISSUE TITLE
Version 2.1.5 dist build is not transpiled

### ISSUE THREAD

**Issue by timothympace** [google-pay/google-pay-button#60]
**Describe the bug** A clear and concise description of what the bug is.

This module is not being transpiled to a distributable that can be used easily. There are two problems I'm running into with webpack.
1. There is an `import React from 'react';` statement in `index.js`.
2. It is compiled to ES6+ language level and requires babel to transpile it.

Is it possible to create a `dist` that is ES5 compatible?

**To Reproduce** Steps to reproduce the behavior:

1. import the module in code
2. bundle with webpack/babel
3. failures unless this module is specifically included

**Expected behavior** A clear and concise description of what you expected to happen.

Should be able to include this in a webpack build with no additional configuration.

**Comment by socsieng** [comment]
Thanks for raising the issue. The intention here was that it would be bring-your-own transpiler/bundler. I can include an ES5 target, however, it will probably only be a minified version. Would that work?

Out of interest, how are you including this resource in your web page?

**Comment by socsieng** [comment]
@timothympace, please have a look at #61 and let me know if it looks okay to you.
