### ISSUE TITLE
React Component not working with NextJS

### ISSUE THREAD

**Issue by mbillz** [google-pay/google-pay-button#71]
**Describe the bug**

I'm getting an import error when using the Google Pay React component with any NextJS projects. I've tried with both a fresh project as well as my company's web project.

**To Reproduce** 

1. Setup blank Typescript enabled NextJS project (`npx create-next-app`, rename file to `pages/index.tsx` and install necessary dependencies when prompted).
2. `npm install` Google Pay React Button and include on page
3. See error thrown

**Expected behavior** 

Expect Google Pay Button to render

**Screenshots** 

<img width="989" alt="Screen Shot 2021-02-05 at 3 22 18 PM" src="https://user-images.githubusercontent.com/5149404/107099257-08937880-67c6-11eb-80c8-2a3c9bc6ee34.png">

**Component information:**

- Component
  - [X] React component (`@google-pay/button-react`)
- Component version 2.1.5

**Environment:**

- Device: MacBook Pro 15-inch, 2019
- OS: Mac OS 10.15.7
- Browser: Chrome 88.0.4324.146
- Country/region: US

**Comment by socsieng** [comment]
Should be fixed in v2.2.0.

Release is pending some additional checks.

**Comment by socsieng** [comment]
[`v2.2.0` released to npm](https://www.npmjs.com/package/@google-pay/button-react/v/2.2.0).
