### ISSUE TITLE
payment Rezeg mushtaha

### ISSUE THREAD

**Issue by Rezegmushtaha** [google-pay/google-pay-button#75]
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

**Expected behavior** A clear and concise description of what you expected to happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Component information:**

- Component
  - [ ] React component (`@google-pay/button-react`)
  - [ ] Custom element (`@google-pay/button-element`)
  - [ ] Angular component (`@google-pay/button-angular`)
- Component version (e.g. 1.0.0):

**Environment:**

- Device (e.g. iPhone6):
- OS (e.g. iOS8.1):
- Browser (e.g. stock browser, safari)
- Country/region:

**Additional context** Add any other context about the problem here.

**Comment by socsieng** [comment]
Closing this issue because it is blank/default description. Feel free to create another issue with details.
