### ISSUE TITLE
"Cannot read property 'includes' of undefined" when setting environment to "PRODUCTION"

### ISSUE THREAD

**Issue by mbillz** [google-pay/google-pay-button#77]
**Describe the bug** When setting environment as `PRODUCTION` and using `existingPaymentMethodRequired` flag, getting `Cannot read property 'includes' of undefined` error and the Google Pay button no longer shows up.

**To Reproduce** Steps to reproduce the behavior:
- implement Google Pay React component
- set environment to "PRODUCTION" mode
- set `existingPaymentMethodRequired` to `true`
- see error

**Expected behavior** Except Google Pay button to show up

**Screenshots**
<img width="676" alt="Screen Shot 2021-02-25 at 12 23 23 PM" src="https://user-images.githubusercontent.com/5149404/109212418-5b78a400-7764-11eb-9586-34a166d30f8c.png">

**Component information:**

- Component
  - [X] React component (`@google-pay/button-react`)
- Component version (e.g. 1.0.0): 2.2.1

**Environment:**

- Device: MacBook Pro (15-inch, 2019) 
- OS: Catalina 10.15.7
- All browsers
- Country/region: US

**Additional context** 
- Our domain is verified for production in the Google Pay console
- The button works fine when set to `TEST`
- Verified that we are using the correct merchant ID

Here is the code used to render the button:
```
<GooglePay
            existingPaymentMethodRequired
            className="google-pay-button"
            environment="PRODUCTION"
            environment={
              process.env.CALM_ENV === 'production' ? 'PRODUCTION' : 'TEST'
            }
            buttonType="plain"
            buttonSizeMode="fill"
            paymentRequest={{
              apiVersion: 2,
              apiVersionMinor: 0,
              allowedPaymentMethods: [
                {
                  type: 'CARD',
                  parameters: {
                    allowedAuthMethods: ['PAN_ONLY', 'CRYPTOGRAM_3DS'],
                    allowedCardNetworks: ['MASTERCARD', 'VISA'],
                  },
                  tokenizationSpecification: {
                    type: 'PAYMENT_GATEWAY',
                    parameters: {
                      gateway: 'stripe',
                      'stripe:version': '2018-10-31',
                      'stripe:publishableKey': process.env.STRIPE_TOKEN,
                    },
                  },
                },
              ],
              merchantInfo: {
                merchantId: process.env.GOOGLE_PAY_MERCHANT_ID,
                merchantName: 'Calm',
              },
              transactionInfo: {
                totalPriceStatus: 'FINAL',
                totalPriceLabel: 'Total',
                totalPrice:
                  purchaseType?.type === 'freetrial'
                    ? '00.00'
                    : (prices?.current[plan] / 100).toString(),
                currencyCode: prices?.current?.currency || 'USD',
                countryCode: 'US',
              },
            }}
            onLoadPaymentData={paymentRequest => {
              const stripeToken = JSON.parse(
                paymentRequest?.paymentMethodData?.tokenizationData?.token,
              );
              onSubmit(stripeToken);
            }}
            onReadyToPayChange={({ isReadyToPay }) =>
              setIsGoogleAvailable(isReadyToPay)
            }
          />
```

**Comment by socsieng** [comment]
Thanks for the bug report. Are you able to include some of the code that is referenced by the `TypeError`? That is, can you click on the link to the right of the logged error and post a screenshot to that?

Alternatively, are able to provide a link to the application for me to test for myself?

**Comment by mbillz** [comment]
Hi @socsieng! Thanks in advance for your help.

We don't have anything live right now (I just disabled that boolean to get the button functionality), but I'm able to replicate it by spinning up a new NextJS demo app. Let me throw it on Netlify and I'll get you a link in the next couple of hours. 

Here's a screenshot of that code though (line 432 is specifically referenced): 
<img width="1255" alt="Screen Shot 2021-02-25 at 1 52 23 PM" src="https://user-images.githubusercontent.com/5149404/109224359-b1534900-7770-11eb-8d9e-d6bf874f9cc6.png">

Let me know if I can provide anything else

**Comment by socsieng** [comment]
One thing to note is that when running in `PRODUCTION` mode, the website's origin is validated against the `merchantId` (this doesn't happen in `TEST` mode). So one of the prerequisites is that you must have the website registered **and** approved using `https://pay.google.com/business/console/payment/web/YOUR_MERCHANT_ID/add` before it will work in `PRODUCTION` mode.

**Comment by mbillz** [comment]
Thanks for the insight. Apologies if I didn't mention this in the initial post, but the library IS working on production without the `existingPaymentMethodRequired` prop set to true. Here's a screenshot of our business verified: 
![integration_approval](https://user-images.githubusercontent.com/5149404/109227148-b5816580-7774-11eb-889b-80efd8bfa649.jpg)

I suppose putting it throwing it up on Netlify wouldn't help us then since it won't be under our domain name?

**Comment by socsieng** [comment]
> I suppose putting it throwing it up on Netlify wouldn't help us then since it won't be under our domain name?

Correct, it wouldn't help.

Can you confirm that you're testing with `PRODUCTION` applies to the same website URL?

There is another thing to note with `PRODUCTION`/`TEST` behavior is that `existingPaymentMethodRequired` always evaluates to `true` in `TEST` (see https://developers.google.com/pay/api/web/reference/client#isReadyToPay).

**Comment by mbillz** [comment]
Yep, the site we are rendering the Google Pay button on is https://www.calm.com/subscribe which is on the verified domain. And, it's working when the `existingPaymentMethodRequired` prop is removed so I don't think it has to do with the domain.

**Comment by socsieng** [comment]
I was trying to test it out for myself but wasn't able to get the Google Pay button to appear:
![image](https://user-images.githubusercontent.com/2647062/109230382-a05b0580-7779-11eb-92ee-19115bd2a384.png)

Any tips on how to do this? If the button were rendered with `existingPaymentMethodRequired` set to `false`, I could edit the value in the browser and try to reproduce/troubleshoot it myself.

**Comment by mbillz** [comment]
It's actually behind an AB test so it looks like you weren't enrolled. Unfortunately I don't have a good way of getting you enrolled, but you can try logging in with the account you created in a new Incognito window until you see the buttons :laughing:

**Comment by socsieng** [comment]
Got it on the second try:
![image](https://user-images.githubusercontent.com/2647062/109231661-d9947500-777b-11eb-9ef9-5c5bf96a3141.png)

Testing it out now.

**Comment by socsieng** [comment]
I think I've gotten to the bottom of it. I was able to test with two scenarios by setting `existingPaymentMethodRequired` to `true` in the browser:

1. With incognito mode I was able to reproduce the behavior that you've reported
2. Outside of incognito mode (by clearing cookies to make sure I get the Google Pay button) I wasn't able to reproduce

What this suggests is that this is related to incognito mode, or when Google Pay is unable to determine the state of the logged in user and by extension whether or not the user has existing payment methods. If Google Pay is unable to determine that the user has an existing payment method, then the button will be hidden by design.

Are you able to confirm/verify this for yourself?

However, I'm guessing that you want to update the UI based on whether or not the Google Pay button is displayed. If so, you should be looking at the `isButtonVisible` (instead of `isReadyToPay`) property in the `onReadyToPayChange` callback.

```
onReadyToPayChange={({ isButtonVisible, isReadyToPay }) =>
  setIsGoogleAvailable(isButtonVisible)
}
```

**Comment by mbillz** [comment]
Super good insight and very interesting. I was only testing in Incognito so that could certainly be why. Modifying the component in the minified production code is a little bit beyond my skillset 😄 . That still seems like potentially a library issue if the JS is actually erroring in Incognito.

Regardless, the `isButtonVisible` boolean seems like it will solve our issue. Do you have any documentation on that? I'm not seeing it on either the React component docs or in the Google Pay docs.

Thanks for your help! I'll report back tomorrow.

**Comment by socsieng** [comment]
> Do you have any documentation on that? I'm not seeing it on either the React component docs or in the Google Pay docs.

It's specific to the button components defined in this repository, but as you've correctly pointed out, it isn't documented. I'll update the documentation in this repository to reflect.

**Comment by socsieng** [comment]
> Modifying the component in the minified production code is a little bit beyond my skillset 😄 .

Beyond mine as well. I was using [React Developer Tools extension](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) to mess around with the site.

**Comment by mbillz** [comment]
Ah yes, I always forget about React Dev Tools. Thanks for your help! I'm good to close this, I have a solid direction.
