### ISSUE TITLE
Payment button does not open link on mobile

### ISSUE THREAD

**Issue by eventdift** [google-pay/google-pay-button#80]
**Describe the bug**
The example code on stackblitz does not open a payment page, but does so on a desktop browser, or if page is loaded as desktop

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://stackblitz.com/edit/google-pay-react on mobile
2. Click on pay
3. Does not open payment page

**Component information:**

- Component
  - [ ] React component (`@google-pay/button-react`)

**Environment:**

- Device: samsung j5
- OS: android
- Browser: chrome
- Country/region: nigeria/africa

**Comment by socsieng** [comment]
Thanks for reporting. The underlying issue has something to do with how the payment sheet is invoked in StackBlitz (preview iframe) + mobile devices.

Because this isn't a typical use case, I've added workaround with a note to the sample page and link to open the page in a new window.

Please take another look and let me know if this works for you.

**Comment by eventdift** [comment]
Thanks for the reply, but the action is the same even on https://google-pay-react.stackblitz.io/. Its also the same on a page under development i am working on, when visiting on mobile

**Comment by socsieng** [comment]
Are you able to share a screen recording or logs of what you are experiencing?

This is what I see on a Pixel 5 running Chrome:

https://user-images.githubusercontent.com/2647062/112357314-a2d35100-8c8c-11eb-82b8-c5471cd01a33.mp4

Note that the screen recording is blanked out when the payment sheet is displayed.

**Comment by eventdift** [comment]
https://user-images.githubusercontent.com/16232316/112379348-561d6380-8ce8-11eb-801d-f9850019bed7.mp4

Still experiencing the error

**Comment by socsieng** [comment]
Are you able to attach Chrome DevTools to you phone and see if there are any errors in the console?

More context if you need it: https://developer.chrome.com/docs/devtools/remote-debugging/

**Comment by eventdift** [comment]
been able to to see the errors in console, 

> Unable to download payment manifest "<URL>".
![Screen Shot 2021-03-25 at 9 15 02 AM](https://user-images.githubusercontent.com/16232316/112440708-eb514400-8d4a-11eb-8d71-48da08a11f09.png)

**Comment by socsieng** [comment]
Thanks for that. Do you know if there was a HTTP status code attached to
those errors?

And just to confirm, you said that it works when you switch to desktop mode
on the same browser and device?

**Comment by eventdift** [comment]
when i try visiting the address directly (https://pay.google.com/gp/p/payment_method_manifest.json) that generates the error on mobile it displays error 400 (The server cannot process the request because it is malformed). on the same mobile phone if i change the view to desktop it returns result

**Comment by socsieng** [comment]
This is useful information.

There's obviously a difference with the request, are you able to provide the user agent for the request in both modes?

**Comment by eventdift** [comment]
mobile view user agent
Mozilla/5.0 (Linux; Android 8.0.0; SM-G570F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Mobile Safari/537.36

desktop view user agent
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36

**Comment by socsieng** [comment]
I just checked on my mobile device. I get the same "Unable to download payment manifest" errors in the console. However, the payment sheet still comes up.

Do you have get any additional errors in the console when you tap the Google Pay button?

**Comment by eventdift** [comment]
No additional errors, 

So i tried on normal samsung browser on my mobile, and the button works, but does not work on chrome

**Comment by socsieng** [comment]
Still looking into the issue, but I have a potential workaround for you if this is a blocker for you.

It involves using the `onPaymentAuthorized` callback to get Chrome to launch a popup window (like it does for the Samsung browser) instead of trying to invoke the native payment sheet which I suspect isn't installed on your device.

Code sample: https://stackblitz.com/edit/google-pay-react-auth

Add the following to the `paymentRequest`:

```js
const paymentRequest = {
  // ...
  callbackIntents: ["PAYMENT_AUTHORIZATION"]
};
```

And the following callback to the button:

```jsx
<GooglePayButton
  {/* ... */}
  onPaymentAuthorized={() => ({ transactionState: "SUCCESS" })}
/>
```

**Comment by eventdift** [comment]
works, thanks
