### ISSUE TITLE
Google Pay Button Angular component needs to be updated for Angular v12.

### ISSUE THREAD

**Issue by bogacg** [google-pay/google-pay-button#82]
Angular is in version 12 now  but Google Pay Button Angular component here is for previous Angular version, v11.
An update is required.

**Comment by socsieng** [comment]
Hi @bogacg, what's the error you are getting?

I was able to successfully create a new Angular 12 app and install/add Google Pay without any issue. See sample repository: https://github.com/socsieng/ng12-google-pay-example

Let me know how to reproduce.

**Comment by bogacg** [comment]
You are right, my bad. I've had few problems with newly released v12 and since this is the first time I try @google-pay/button-angular immediately thought the culprit is here. Closing.
