### ISSUE TITLE
version problem - can we use this for angular 2 version ?

### ISSUE THREAD

**Issue by vanustongithub17** [google-pay/google-pay-button#97]
This question is related to:

- [ ] React component (`@google-pay/button-react`)
- [ ] Custom element (`@google-pay/button-element`)
- [x] Angular component (`@google-pay/button-angular`)
can we use this for angular 2 version ?

**Comment by socsieng** [comment]
Official support for Angular comes from version 8 onwards. It hasn't been tested for version 2.

That said, if it doesn't work for you. You can use the web component version instead: `@google-pay/button-element`

Please let me know how that goes for you.
